server:
  port: 7977



spring:
  datasource:
    url: jdbc:mysql://192.168.43.112:3306/workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username : root
    password : 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: audit
    mail-server-host: smtp.qq.com
    mail-server-port: 465
    mail-server-user-name: 3623509067@qq.com
    mail-server-password: gzgjijkzlzvachjd
    mail-server-use-ssl: true